c_compiler:
  - gcc                      # [linux]
  - clang                    # [osx]
  - vs2019                   # [win]
c_compiler_version:            # [unix]
  - 14                         # [osx]
  - 10                         # [linux]
cxx_compiler:
  - gxx                      # [linux]
  - clangxx                  # [osx]
  - vs2019                   # [win]
cxx_compiler_version:          # [unix]
  - 14                         # [osx]
  - 10                         # [linux]
llvm_openmp:                   # [osx]
  - 14                         # [osx]

python:
  - 3.8

setuptools:
  - 49.6

boost:
  - 1.77

pin_run_as_build:
  boost:
    max_pin: x.x
