{% set version = '0.0.0' %}

package:
  name: versiontestqt
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('versiontestqt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja  # [unix]
    - cmake
    - git
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]

  host:
    - versiontest {{ version }}
    - python {{ python }}
    - pyqt {{ pyqt }}
    - qscintilla2 {{ qscintilla2 }}
    - versioningit

  run:
    - matplotlib {{ matplotlib }}
    - qtpy
    - python

outputs:
  - name: versiontestqt
    files:
      - helloworld.py
